### ISSUE TITLE
License required

### ISSUE THREAD

**Issue by sandercox** [Thomas-Sparber/wmi#11]
Thanks for the hardwork on creating this library. I'd like to use it in our software but to be able to use the library a MIT / BSD / LGPL style license would be required. Would it be possible to add this to the repository?

**Comment by Thomas-Sparber** [comment]
Hi sandercox,
thanks for the appreciation!
You can see this library as a "gift" - use it however you like!
Although, of course I am happy about a remark in your software! :-)
Regards

**Comment by sandercox** [comment]
I figured as much but from a legal sense I'd appreciate a real license file - GitHub offers templates for that to make it super easy for you: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by Thomas-Sparber** [comment]
OK I understand. What do would you think about the same license model as stb (https://github.com/nothings/stb)?
Would that be good for you?

**Comment by sandercox** [comment]
Yes that would work fine for me.

Thanks!
________________________________

**Comment by Thomas-Sparber** [comment]
Done :-)

**Comment by sandercox** [comment]
Thanks! I'll do a pull request next week with some extra data blocks!
