### ISSUE TITLE
LNK2001 - Unresolved External Symbol

### ISSUE THREAD

**Issue by MCgamin1738** [Thomas-Sparber/wmi#12]
Hi, 

After Trying To Build My Project With VS 2019, I Got 2 Errors:

unresolved external symbol _IID_IWbemLocator
unresolved external symbol _CLSID_WbemLocator

Both Of These Are On Line 26 In wmi.cpp

**Comment by Thomas-Sparber** [comment]
Hi,

can you please try to add wbemuuid.lib as link dependency to your VS project?

**Comment by MCgamin1738** [comment]
I Just Did That, It Worked, Thanks!
