### ISSUE TITLE
System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by sultanberisa** [Thomas-Sparber/wmi#25]
Hello! I have a C++ clr project with windows forms and im using the WMI library to extract some data which i need. The program works completely fine on my computer, and several other computers, however on two computers that i've tested it on it did not work. It returned this error:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at _CxxThrowException(Void* , _s__ThrowInfo* )
   at foreachProperty(IWbemClassObject* object, function<bool __cdecl(std::basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> > const \&\,std::basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> > const \&)>* fn)
   at Wmi.query.<lambda_7e7408e64a50b6b7b46c87ce6fa9a552>.()(<lambda_7e7408e64a50b6b7b46c87ce6fa9a552>* , IWbemClassObject* object)
   at std._Func_class<bool,IWbemClassObject *>.()(_Func_class<bool\,IWbemClassObject \*>* , IWbemClassObject* <_Args_0>)
   at foreachObject(IEnumWbemClassObject* pClassObject, function<bool __cdecl(IWbemClassObject \*)>* fn)
   at Wmi.query(basic_string<char\,std::char_traits<char>\,std::allocator<char> >* q, basic_string<char\,std::char_traits<char>\,std::allocator<char> >* p, WmiResult* out)
   at Wmi.retrieveWmi<struct Wmi::Win32_ComputerSystem>(Win32_ComputerSystem* out)
   at Wmi.retrieveWmi<struct Wmi::Win32_ComputerSystem>(Win32_ComputerSystem* )
   at getData(basic_string<char\,std::char_traits<char>\,std::allocator<char> >* type)
   at macStr()
   at Project2.MyForm.MyForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

I have no idea why this is happened and frankly it's quite puzzling to see that it works fine on most computers, just not this one?

Here is the code for the data I get:
```
    try
    {
    Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>();
    Win32_ComputerSystemProduct product = retrieveWmi<Win32_ComputerSystemProduct>();
    Win32_OperatingSystem os_info = retrieveWmi<Win32_OperatingSystem>();
    Win32_BIOS bios = retrieveWmi<Win32_BIOS>();

    string WindowsVersion = os_info.Caption;
    string LastWindowsUpdate = getUpdate().c_str();
    string brukernavn = computer.UserName;
    string tyverimerke = computer.Name.c_str();
    string InstallationDate = registry_read("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion", "InstallDate", REG_DWORD);
    string Manufacturer = registry_read("HARDWARE\\DESCRIPTION\\System\\BIOS", "BIOSVendor", REG_SZ);
    string Model = product.Version;
    string Serial = bios.Serial;
    string Warranty = GetWarrantyLenovo(Serial, hnd, ret);
    printf("warranty %s", Warranty.c_str());

    printf("\n Siste gang du oppdaterte pc'en din var: %s", getUpdate().c_str(), "\n");

    //just setting up some strings, removing things and adding things etc



    char ch = '\\';
    // Get the position of first occurrence of character
    std::size_t pos = brukernavn.find(ch);
    // Check if index position is valid  
    if (pos != std::string::npos)
    {
        // Remove all characters before the given position 
        brukernavn = brukernavn.substr(pos + 1);
    }

    WindowsVersion =/* Microsoft + */WindowsVersion;
    PCModel = Manufacturer + " " + Model; //kan hende manufacturer må bare kommenteres ut siden det ser ut som via wmi så henter den ut hel string m/ manufacturer via product.Name


    long int T = TestGetInstallDate();

    std::string InstallDateNonUnix = unixTimeToHumanReadable(T); //trengs ikke....

    //std::cout << InstallDateNonUnix;

    if (os_info.OSArchitecture.find("64") != std::string::npos)
        WindowsVersion = WindowsVersion + sixtyfour;

    else if (os_info.OSArchitecture.find("32") != std::string::npos)
        WindowsVersion = WindowsVersion + thirtytwo;


    //lastupdatenew

    String^ macStrNew = gcnew String(macStr);
    String^ szLocalIPNew = gcnew String(szLocalIP);
    String^ LastWindowsUpdateNew = gcnew String(LastWindowsUpdate.c_str());
    String^ PCModelNew = gcnew String(PCModel.c_str());
    String^ SerialNew = gcnew String(Serial.c_str());
    String^ WindowsVersionNew = gcnew String(WindowsVersion.c_str());
    String^ InstallDateNonUnixNew = gcnew String(InstallDateNonUnix.c_str());
    String^ tyverimerkeNew = gcnew String(tyverimerke.c_str());
    String^ brukernavnNew = gcnew String(brukernavn.c_str());
    String^ warrantyNew = gcnew String(Warranty.c_str());


    if (type == "macStr") {
        return macStrNew;
    }
    else if (type == "szLocalIP") {
        return szLocalIPNew;
    }
    else if (type == "LastWindowsUpdate") {
        return LastWindowsUpdateNew;
    }
    else if (type == "PCModel") {
        return PCModelNew;
    }
    else if (type == "Serial") {
        return SerialNew;
    }
    else if (type == "WindowsVersion") {
        return WindowsVersionNew;
    }
    else if (type == "InstallDateNonUnix") {
        return InstallDateNonUnixNew;
    }
    else if (type == "tyverimerke") {
        return tyverimerkeNew;
    }
    else if (type == "brukernavn") {
        return brukernavnNew;
    }
    else if (type == "warranty")
    {
        return warrantyNew;
    }
    // Example for Windows Embedded
        //UWF_Filter filter = retrieveWmi<UWF_Filter>();
        //cout << "UWF Filter enabled:" << filter.CurrentEnabled << std::endl;
    }
    catch (const WmiException& ex) {
        cerr << "Wmi error: " << ex.errorMessage << ", Code: " << ex.hexErrorCode() << endl;
    }
```

**Comment by sultanberisa** [comment]
Also getting a different issue on a different computer;
`************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at GetWarrantyLenovo(basic_string<char\,std::char_traits<char>\,std::allocator<char> >* , basic_string<char\,std::char_traits<char>\,std::allocator<char> >* serialNum, Void* hnd, CURLcode ret)
   at getData(basic_string<char\,std::char_traits<char>\,std::allocator<char> >* type)
   at macStr()
   at Project2.MyForm.MyForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by sultanberisa** [comment]
I have managed to get an more exact error:
![image](https://user-images.githubusercontent.com/99986214/180718108-c2c6a2fc-6801-410f-b206-6b8cc5a5fa1e.png)
Any ideas guys? Please i need some help. @Thomas-Sparber

**Comment by Thomas-Sparber** [comment]
Hi @sultanberisa 
thanks for your detailed analysis. It seems like you are trying to fetch some data of type OEMLogoBitmap which my WMI currently not supports.
If I have a look at Win32_ComputerSystem (https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-computersystem) I can see that there is indeed some data of this type. I guess on the machines where it is working this data is empty and therefore it works as it should.
The big question now is: Do you need OEMLogoBitmap?
If yes, you probably need to implement it and make a pull request or wait until I implement it.
If not then I guess you just need to specify which Parameters should be fetched in `retrieveWmi` (see line 49 in main.cpp) and you should be fine

**Comment by sultanberisa** [comment]
> 

Thank you so much for the response Thomas. No, I actually do not need OEMlogobitmap nor have i to my knowledge attempted to retrieve it. Line 49, this? ` if (os_info.OSArchitecture.find("64") != std::string::npos)
        WindowsVersion = WindowsVersion + sixtyfour;

    else if (os_info.OSArchitecture.find("32") != std::string::npos)
        WindowsVersion = WindowsVersion + thirtytwo;`

This is just checking if OS is 64 bit or 32 bit, because it includes a windows form that displays a line with windows version etc including the architecture version. Is this what's causing the issue? I uncommented OEMlogobitmap in the classes and was going to give it a go that way to be honest.

**Comment by Thomas-Sparber** [comment]
You can execute `retrieveWmi` and passing the columns you want to retrieve, e.g.

    Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>("UserName,User");

**Comment by sultanberisa** [comment]
> You can execute `retrieveWmi` and passing the columns you want to retrieve, e.g.
> 
> ```
> Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>("UserName,User");
> ```

Okay, so that means if i would want to save it in variables i would have to do one for each variable i want to extract? for example

Win32_OperatingSystem os_info = retrieveWmi<Win32_OperatingSystem>("Caption"); etc

Or can i put in multiple columns and just call them like normal?

**Comment by Thomas-Sparber** [comment]
You can put multiple columns in one call (comma separated) as I did it in my example: "UserName,User"

**Comment by sultanberisa** [comment]
> You can put multiple columns in one call (comma separated) as I did it in my example: "UserName,User"

How would it be called and saved into a string then? Because this is what happens when i use your way of calling it: 
![image](https://user-images.githubusercontent.com/99986214/180781171-ffc12dcc-42ee-4d5a-ae0f-96f47c1fc3f3.png)

Completely empty, breaks the rest of the WMI calls too.

**Comment by Thomas-Sparber** [comment]
To me it seems like you are only using the columns User and UserName so that's why I suggested to only retrieve those columns.
But maybe you are using different columns of Win32_ComputerSystem too?? Check your code for which columns you need and then only retrieve those columns.

**Comment by sultanberisa** [comment]
string WindowsVersion = os_info.Caption;
    string LastWindowsUpdate = getUpdate().c_str();
    string brukernavn = computer.UserName;
    string tyverimerke = computer.Name;
    string InstallationDate = registry_read("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion", "InstallDate", REG_DWORD);
    string Manufacturer = product.Version;
    string Model = product.Name;
    string Serial = bios.Serial;

Im using alot more than user and username. My point is, the pointers i make here:
Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>();
    Win32_ComputerSystemProduct product = retrieveWmi<Win32_ComputerSystemProduct>();
    Win32_OperatingSystem os_info = retrieveWmi<Win32_OperatingSystem>();
    Win32_BIOS bios = retrieveWmi<Win32_BIOS>();

I call and point to string variables, but how would I do that if im using columns the way you're describing? Sorry if i'm missing something, i am a newbie at coding

**Comment by Thomas-Sparber** [comment]
You do like the following:

    Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>();

This line executes the WMI request and retrieves all columns for Win32_ComputerSystem (see https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-computersystem): `AdminPasswordStatus`, `AutomaticManagedPagefile`, `AutomaticResetBootOption`, ...

But you probably don't need all columns from Win32_ComputerSystem, just a few, e.g. `User`, `UserName`, `Caption`, etc. So you go through your code and check which columns you use. At the end you have a list of maybe 10 columns. So you modify your code like the following:

    Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>("User,UserName,Caption,<all-the-other-columns-you-need>");

You maybe start by doing this for Win32_ComputerSystem because the error is coming from this call but you can also do it for the other WMI classes, e.g. Win32_ComputerSystemProduct, Win32_OperatingSystem, Win32_BIOS, etc.

**Comment by sultanberisa** [comment]
Ah i see, but i can still call to the columns like i regularly do? string brukernavn = computer.UserName for example?

**Comment by sultanberisa** [comment]
Because this is what happens when i do it your way:
![image](https://user-images.githubusercontent.com/99986214/181167873-a1cdc43d-47ef-489c-94cc-b4684b465203.png)

Code:
` Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>("User,UserName,Manufacturer"); //here 
        printf("\nretrieveWmi<Win32_ComputerSystem>()\n");
        Win32_ComputerSystemProduct product = retrieveWmi<Win32_ComputerSystemProduct>();
        printf("\nretrieveWmi<Win32_ComputerSystemProduct>()\n");
        Win32_OperatingSystem os_info = retrieveWmi<Win32_OperatingSystem>();
        printf("\n retrieveWmi<Win32_OperatingSystem>();\n");
        Win32_BIOS bios = retrieveWmi<Win32_BIOS>();
        printf("\nretrieveWmi<Win32_BIOS>();\n");

        string WindowsVersion = os_info.Caption;
        string LastWindowsUpdate = getUpdate().c_str();
        string brukernavn = computer.UserName; //variable for username here
        string tyverimerke = computer.Name.c_str(); //variable for computer name here
        string InstallationDate = registry_read("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion", "InstallDate", REG_DWORD);
        //string Manufacturer = registry_read("HARDWARE\\DESCRIPTION\\System\\BIOS", "BIOSVendor", REG_SZ);
        string Manufacturer = computer.Manufacturer; //and variable for manufacturer here
        string Model = product.Version;
        string Serial = bios.Serial;
        string Warranty = "";`

**Comment by sultanberisa** [comment]
Seemed to be able to find atleast whats causing that error with the columns, its when i enter multiple Columns. If i only get one column, eg `Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>("Manufacturer");`
it works flawlessly, however Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>("User,UserName,Caption"); does not and breaks the rest of the wmi calls aswell causing no info to be returned from the wmi calls.

**Comment by sultanberisa** [comment]
Really really strange, seems like the order of the colums that you pick matter.
I just made it work, by doing this:
`Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>("UserName,Name,Manufacturer");`

But this for example wouldn't work: 
`Win32_ComputerSystem computer = retrieveWmi<Win32_ComputerSystem>("User,UserName,Manufacturer");`

But atm it's working for me so i'm happy about that, im going to test in a bit if that solved the error or not, as the error only displayed on a select few machines. Not sure if its designed in the way that the column order should have anything to say, if it's not supposed to be like that maybe @Thomas-Sparber you should take a look at it? Doesn't seem like thats what its supposed to do considering you didn't do it in your example you gave to me? 👍

**Comment by Thomas-Sparber** [comment]
Glad to hear you managed to get it working! :-)
I don't have any influence on the order. The columns are passed 1:1 to WMI as WQL - seems like there the orders matters
