### ISSUE TITLE
Allow publish of pre-build packages for mingw and msvc.

### ISSUE THREAD

**Issue by PerryWerneck** [Thomas-Sparber/wmi#27]
I'm working in a github action to publish pre build packages for mingw and msvc (here: https://github.com/PerryWerneck/wmi/blob/master/.github/workflows/publish.yml) and I'm wondering if you want to use it in the original wmi package (this project). Before submit the PR I think you need to do some settings in the project...

- Create at least one version tag (I used 1.0)
- Allow actions to publish releases

**Comment by Thomas-Sparber** [comment]
Hi PerryWerneck,

yes sure, that sounds like a great idea!
I just created version v1.0.
How can I allow actions to publish releases? I went under "Actions" but it seems like I need to create an `yml` file there.
Can you guide me what I need to do please?

Thanks

**Comment by PerryWerneck** [comment]
I created the yml file, will send you a PR as soon as possible.

**Comment by Thomas-Sparber** [comment]
Perect, I just merged it and it seems to be working:

![image](https://github.com/Thomas-Sparber/wmi/assets/20128917/7973081a-72f9-4884-8947-c9e3c1642433)

**Comment by PerryWerneck** [comment]
Hi,

Ops! My fault! It will build and publish in every commit or pull request on master branch. I'm used to allwais keep my master branch protected and work using a develop branch then use a PR to send changes to master. Will check how to publish only in releases and submit a new PR fixing it. 

For now I think it's great. Just checked the msvc zip file and seens ok to me.
