### ISSUE TITLE
Wmi error: Error getting next element: Unknown Error

### ISSUE THREAD

**Issue by ahmad-kemsan** [Thomas-Sparber/wmi#7]
Hi, 

I tried creating a new class for CPU but got this error:

 **"Wmi error: Error getting next element: Unknown Error".**

```cpp
struct Win32_cpu
	{
		Win32_cpu() :
			Name()
			
			
		{ }
		void setProperties(const WmiResult& result, std::size_t index) {
			result.extract(index, "Name", (*this).Name);
			
		}
		static std::string getWmiClassName()
		{
			return "Win32_cpu";
		}

		std::string Name;
		

};
```

**Comment by Thomas-Sparber** [comment]
Hi ahmad-kemsan,

Win32_cpu is no valid WMI class.
Here is a list of all valid WMI classes: https://www.activexperts.com/admin/scripts/wmi/
I think you are looking for Win32_Processor

Regards
Thomas
